version: 0.2

phases:
  install:
    commands:
      - pip install semgrep
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /tmp
      - /tmp/trivy --version

  build:
    commands:
      - semgrep --config auto --error .
      - /tmp/trivy fs --exit-code 1 --severity HIGH,CRITICAL .
